[package]
name = "puv"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
log = "0.4"
memchr = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["io-util"] }
tracing = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["fs", "process"] }

uv-pep440 = "=0.0.29"
uv-pep508 = "=0.0.29"
uv-scripts = "=0.0.29"
uv-workspace = "=0.0.29"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
